// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5mH2N1KD-sgBccKLiIq_bhh-TG2ifJyU',
    appId: '1:104688168952:web:6f4558bba2b3ee5b62b00d',
    messagingSenderId: '104688168952',
    projectId: 'glory-grid-b90a3',
    authDomain: 'glory-grid-b90a3.firebaseapp.com',
    storageBucket: 'glory-grid-b90a3.firebasestorage.app',
    measurementId: 'G-VZXQKF4GZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEKfhKv6gwEDF-X6MIs1dZle9hOaMesVs',
    appId: '1:104688168952:android:322e781e28d2d49462b00d',
    messagingSenderId: '104688168952',
    projectId: 'glory-grid-b90a3',
    storageBucket: 'glory-grid-b90a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKoakvnOKdjkwN-fiduAsPy1ex_oFrus',
    appId: '1:104688168952:ios:e70a3e4382c6364e62b00d',
    messagingSenderId: '104688168952',
    projectId: 'glory-grid-b90a3',
    storageBucket: 'glory-grid-b90a3.firebasestorage.app',
    iosBundleId: 'com.legendarypixels.glorygrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKoakvnOKdjkwN-fiduAsPy1ex_oFrus',
    appId: '1:104688168952:ios:e70a3e4382c6364e62b00d',
    messagingSenderId: '104688168952',
    projectId: 'glory-grid-b90a3',
    storageBucket: 'glory-grid-b90a3.firebasestorage.app',
    iosBundleId: 'com.legendarypixels.glorygrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5mH2N1KD-sgBccKLiIq_bhh-TG2ifJyU',
    appId: '1:104688168952:web:3ede78a24b9f319162b00d',
    messagingSenderId: '104688168952',
    projectId: 'glory-grid-b90a3',
    authDomain: 'glory-grid-b90a3.firebaseapp.com',
    storageBucket: 'glory-grid-b90a3.firebasestorage.app',
    measurementId: 'G-8XCKK3ZMEQ',
  );
}
